### ISSUE TITLE
xshell7.1

### ISSUE THREAD

**Issue by 21ki** [RowTeam/SharpDecryptPwd#3]
![QQ图片20220806075049](https://user-images.githubusercontent.com/24515576/183224541-a55b8b96-8e06-420f-8753-88d9049a5808.png)

感觉密码还是没有解密成功

**Comment by RcoIl** [comment]
你看下使用 https://github.com/JDArmy/SharpXDecrypt 是否可以解出来。

**Comment by 21ki** [comment]
> 你看下使用 https://github.com/JDArmy/SharpXDecrypt 是否可以解出来。

SharpXDecrypt 密码为空 win11 xshell7.1
![image](https://user-images.githubusercontent.com/24515576/183224613-7223a7e4-d3db-4498-9be5-5aae441ea5d1.png)
同环境下navicat是可以解出来的

**Comment by 21ki** [comment]
也是不行的

**Comment by RcoIl** [comment]
![image](https://user-images.githubusercontent.com/16411168/183332708-f54f6cfe-9649-4328-948f-e566144b7d22.png)

我这边本地测试是没有任何问题的、

**Comment by 21ki** [comment]
能否远程看一眼，我办公司电脑是win10家里电脑win11都不行
我的是xshell6然后升级到xshell7的，不知道有没有关系

**Comment by 21ki** [comment]
两个软件我都试了，都不行的。您方便向日葵 或者什么软件帮忙看下吗？

RcoIl ***@***.***> 于2022年8月5日周五 11:53写道：

**Comment by RcoIl** [comment]
远程这个没办法了。你重新安装一个 7.1的版本试试。我这边测试的是刚安装的，然后就成功了的、

**Comment by 21ki** [comment]
知道哪里的问题了,xshell打开的时候不能设置密码，如果设置了这个密码就解不开了.请知悉

**Comment by RcoIl** [comment]
多谢、加了密码就没研究过了 = =、
